// File generated by FlutterFire CLI.
// 이 파일은 `flutterfire configure` 명령어로 자동 생성됩니다.
//
// 생성 방법:
// 1. Terminal에서 프로젝트 루트 디렉토리로 이동
// 2. 다음 명령어 실행:
//    $ firebase login
//    $ dart pub global activate flutterfire_cli
//    $ flutterfire configure
//
// 위 명령어를 실행하면 이 파일이 자동으로 생성됩니다.
//
// 수동으로 설정하려면:
// 1. Firebase Console에서 프로젝트 설정 페이지로 이동
// 2. "일반" 탭에서 각 앱의 Firebase SDK 스니펫 확인
// 3. 아래 값들을 해당 값으로 교체

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsj-6v7Mo2s7KfNZ_4dFQVN4o4u89aH-s',
    appId: '1:454975006913:android:5293cb3faaf48aff6c0c40',
    messagingSenderId: '454975006913',
    projectId: 'fcmpractice-e8dff',
    storageBucket: 'fcmpractice-e8dff.firebasestorage.app',
  );

  // TODO: flutterfire configure 명령어를 실행하여 아래 값들을 자동으로 생성하세요

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCljiZ1z0QJ9J0YuibbexfbsJQqyiz4_c',
    appId: '1:454975006913:ios:cec7269b79df1c276c0c40',
    messagingSenderId: '454975006913',
    projectId: 'fcmpractice-e8dff',
    storageBucket: 'fcmpractice-e8dff.firebasestorage.app',
    iosBundleId: 'com.ahyeonlee.jakbuFlutter',
  );

}